# Generated by Django 4.1.7 on 2023-05-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_rename_location_id_representation_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.type')),
            ],
            options={
                'db_table': 'artist_type',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='types',
            field=models.ManyToManyField(through='catalogue.ArtistType', to='catalogue.type'),
        ),
    ]
