# Generated by Django 4.1.7 on 2023-05-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_artisttype_artist_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='artists',
            field=models.ManyToManyField(through='catalogue.ArtistType', to='catalogue.artist'),
        ),
        migrations.CreateModel(
            name='ArtistTypeShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artisttype')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.show')),
            ],
            options={
                'db_table': 'artist_type_show',
            },
        ),
    ]
