# Generated by Django 4.1.7 on 2023-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_type_artists_artisttypeshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='artist_types',
            field=models.ManyToManyField(through='catalogue.ArtistTypeShow', to='catalogue.artisttype'),
        ),
    ]
