# Generated by Django 4.1.7 on 2023-05-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_show_artist_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='artist_types',
            new_name='artist_type',
        ),
    ]
