# Generated by Django 4.1.7 on 2023-05-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_rename_artist_types_show_artist_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.user')),
            ],
            options={
                'db_table': 'role_user',
            },
        ),
    ]
