# Generated by Django 4.1.7 on 2023-05-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_roleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.representation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.user')),
                ('places', models.IntegerField()),
            ],
            options={
                'db_table': 'representation_user',
            },
        ),
    ]
