# Generated by Django 4.1.7 on 2023-05-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_representationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(through='catalogue.RoleUser', to='catalogue.user'),
        ),
    ]
