# Generated by Django 4.1.7 on 2023-05-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_role_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepresentationUser',
            new_name='Reservation',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
    ]
