# Generated by Django 4.1.7 on 2023-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_rename_representationuser_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
